### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CAPI2'

### ISSUE THREAD

**Issue by zopyx** [plone/buildout.coredev#341]
A fresh master checkout gives me the following error:

```
ajung@dev.zopyx.com:~/sandboxes/buildout.coredev> bin/instance fg
Traceback (most recent call last):
  File "bin/instance", line 265, in <module>
    + sys.argv[1:]))
  File "/home/ajung/.buildout/eggs/plone.recipe.zope2instance-4.2.22-py2.7.egg/plone/recipe/zope2instance/ctl.py", line 610, in main
    options.realize(args, doc=__doc__)
  File "/home/ajung/.buildout/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/zopectl.py", line 162, in realize
    ZDOptions.realize(self, *args, **kw)
  File "/home/ajung/.buildout/eggs/zdaemon-4.2.0-py2.7.egg/zdaemon/zdoptions.py", line 294, in realize
    self.load_schema()
  File "/home/ajung/.buildout/eggs/zdaemon-4.2.0-py2.7.egg/zdaemon/zdoptions.py", line 342, in load_schema
    self.schema = ZConfig.loadSchema(self.schemafile)
  File "/home/ajung/.buildout/eggs/ZConfig-3.1.0-py2.7.egg/ZConfig/loader.py", line 49, in loadSchema
    return SchemaLoader().loadURL(url)
  File "/home/ajung/.buildout/eggs/ZConfig-3.1.0-py2.7.egg/ZConfig/loader.py", line 83, in loadURL
    return self.loadResource(r)
  File "/home/ajung/.buildout/eggs/ZConfig-3.1.0-py2.7.egg/ZConfig/loader.py", line 229, in loadResource
    schema = ZConfig.schema.parseResource(resource, self)
  File "/home/ajung/.buildout/eggs/ZConfig-3.1.0-py2.7.egg/ZConfig/schema.py", line 32, in parseResource
    xml.sax.parse(resource.file, parser)
  File "/usr/lib64/python2.7/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 304, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/home/ajung/.buildout/eggs/ZConfig-3.1.0-py2.7.egg/ZConfig/schema.py", line 108, in startElement
    getattr(self, "start_" + name)(attrs)
  File "/home/ajung/.buildout/eggs/ZConfig-3.1.0-py2.7.egg/ZConfig/schema.py", line 311, in start_import
    src = self._loader.schemaComponentSource(pkg, file)
  File "/home/ajung/.buildout/eggs/ZConfig-3.1.0-py2.7.egg/ZConfig/loader.py", line 246, in schemaComponentSource
    __import__(package)
  File "/home/ajung/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZServer/__init__.py", line 41, in <module>
    from HTTPServer import zhttp_server, zhttp_handler
  File "/home/ajung/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZServer/HTTPServer.py", line 44, in <module>
    from HTTPResponse import make_response
  File "/home/ajung/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZServer/HTTPResponse.py", line 29, in <module>
    from ZPublisher.HTTPResponse import HTTPResponse # XXX WTF?
  File "/home/ajung/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/__init__.py", line 22, in <module>
    from Publish import publish_module, Retry
  File "/home/ajung/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/Publish.py", line 21, in <module>
    from Request import Request
  File "/home/ajung/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/Request.py", line 13, in <module>
    import HTTPRequest
  File "/home/ajung/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/HTTPRequest.py", line 39, in <module>
    from AccessControl.tainted import TaintedString
  File "/home/ajung/.buildout/eggs/AccessControl-3.0.13-py2.7-linux-x86_64.egg/AccessControl/__init__.py", line 16, in <module>
    from AccessControl.Implementation import setImplementation
  File "/home/ajung/.buildout/eggs/AccessControl-3.0.13-py2.7-linux-x86_64.egg/AccessControl/Implementation.py", line 96, in <module>
    setImplementation("C")
  File "/home/ajung/.buildout/eggs/AccessControl-3.0.13-py2.7-linux-x86_64.egg/AccessControl/Implementation.py", line 51, in setImplementation
    from AccessControl import ImplC as impl
  File "/home/ajung/.buildout/eggs/AccessControl-3.0.13-py2.7-linux-x86_64.egg/AccessControl/ImplC.py", line 17, in <module>
    from AccessControl.cAccessControl import rolesForPermissionOn
AttributeError: 'module' object has no attribute 'CAPI2'

```

**Comment by tomgross** [comment]
It seems a (version) issue with your system Python. Did you try an virtualenv? I found this the safest way to escape the setuptools version hell currently:
Try 
```
git clone https://github.com/plone/buildout.coredev.git
cd buildout.coredev
virtualenv .
bin/pip install -r requirements.txt
bin/buildout
```
See https://github.com/plone/Products.CMFPlone/issues/2001

**Comment by zopyx** [comment]
I am always using virtualenv. I have not seen this particular error in my life. The buildout.coredev btw. uses bootstrap.sh meanwhile.

**Comment by tomgross** [comment]
The part
```
 File "/usr/lib64/python2.7/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 304, in start_element
```
looks suspicious

**Comment by gforcada** [comment]
@zopyx did you solve it? If not, please reopen.

**Comment by dals83** [comment]
And if you solved it, can you then please write the solution here?

**Comment by Rotonen** [comment]
This happens if you've somehow managed to build `ExtensionClass` without the C extensions and try to import `AccessControl`.

https://github.com/zopefoundation/ExtensionClass/blob/825fbf48a01eaf70d273ca9e9175f7465b38ba14/setup.py#L26-L31

`AccessControl` blindly depends on `ExtensionClass` having built its C extension.

**Comment by nileshgulia1** [comment]
Did anyone solved above error, I am getting the same error in installing my plone-react backend instance.

**Comment by zopyx** [comment]
I can not recall how my solution looked like...did not encounter the error anymore lately.

**Comment by sunew** [comment]
@nileshgulia1 try to delete the ExtensionClass egg you are using - it will be placed in your buildout cache.
Check your bin/instance for the location.
And then make sure you have the needed dependencies on your system, and rerun buildout.
See here: https://docs.plone.org/manage/installing/requirements.html

**Comment by laulaz** [comment]
Same error here (only) after having set `PURE_PYTHON=1` to debug permissions issue.
