### ISSUE TITLE
Robot initialization/buildout errors

### ISSUE THREAD

**Issue by thet** [plone/buildout.coredev#548]
When running my PLIP job for https://github.com/plone/buildout.coredev/blob/5.2/plips/plip-1653-staticresources.cfg this results in the following error:

https://jenkins.plone.org/view/PLIPs/job/plip-plone-staticresources/14/console

```
+ return_code=all_right
+ export PATH=/usr/lib/chromium-browser:/home/jenkins/shiningpanda/jobs/dd5c15c8/virtualenvs/d41d8cd9/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jenkins/.local/bin:/home/jenkins/.local/bin:/home/jenkins/.local/bin
+ export ROBOT_BROWSER=chrome
+ xvfb-run -a --server-args=-screen 0 1920x1200x24 bin/alltests --xml --all
/usr/bin/xvfb-run: 184: /usr/bin/xvfb-run: bin/alltests: not found
+ return_code=127
+ xvfb-run -a --server-args=-screen 0 1920x1200x24 bin/alltests-at --xml
/usr/bin/xvfb-run: 184: /usr/bin/xvfb-run: bin/alltests-at: not found
+ return_code=127
+ [ 127 = all_right ]
+ exit 127
Build step 'Virtualenv Builder' marked build as failure
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Robot results publisher started...
-Parsing output xml:
Failed!
hudson.AbortException: No files found in path /home/jenkins/workspace/plip-plone-staticresources@2/parts/test with configured filemask: robot_output.xml
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:78)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:54)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3085)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to Node5
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1071)
		at hudson.FilePath.act(FilePath.java:1060)
		at hudson.plugins.robot.RobotParser.parse(RobotParser.java:49)
		at hudson.plugins.robot.RobotPublisher.parse(RobotPublisher.java:224)
		at hudson.plugins.robot.RobotPublisher.perform(RobotPublisher.java:246)
		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
		at hudson.model.Build$BuildExecution.post2(Build.java:186)
		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
		at hudson.model.Run.execute(Run.java:1840)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Email was triggered for: Always
Sending email for trigger: Always
Sending email to: johannes@raggam.co.at
Finished: FAILURE
```

**Comment by gforcada** [comment]
@thet all PLIP jobs needed to get an update on their script.

It was done at https://github.com/plone/jenkins.plone.org/commit/6739adac10644f7dc4cb3ed922781b428255ebe4 and deployed already.

I already started a new job: https://jenkins.plone.org/view/PLIPs/job/plip-plone-staticresources/16/console
