### ISSUE TITLE
Problems with MacOS on GitHub Actions

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/buildout.coredev#922]
This is likely because MacOS on the runners is being [upgraded](https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/) from 12 to 14.  So we may need to explicitly use version 12 (or maybe 13) in some cases.

Sample error:

```
Run actions/setup-python@v3
  with:
    python-version: 3.8
    cache: pip
    token: ***
Version 3.8 was not found in the local cache
Error: Version 3.8 with arch arm64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

This is expected for Python 3.8 and 3.9 now it seems.

But I also saw a [weird error on Python 3.10](https://github.com/plone/buildout.coredev/actions/runs/8821773238/job/24218407231):

```
ImportError: dlopen(/Users/runner/work/buildout.coredev/buildout.coredev/eggs/charset_normalizer-3.3.2-py3.10-macosx-11-x86_64.egg/charset_normalizer/md.cpython-310-darwin.so, 0x0002): tried: '/Users/runner/work/buildout.coredev/buildout.coredev/eggs/charset_normalizer-3.3.2-py3.10-macosx-11-x86_64.egg/charset_normalizer/md.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/buildout.coredev/buildout.coredev/eggs/charset_normalizer-3.3.2-py3.10-macosx-11-x86_64.egg/charset_normalizer/md.cpython-310-darwin.so' (no such file), '/Users/runner/work/buildout.coredev/buildout.coredev/eggs/charset_normalizer-3.3.2-py3.10-macosx-11-x86_64.egg/charset_normalizer/md.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

I wondered if that might have something to do with an egg cache being restored that contains incompatible eggs that Buildout then thinks are usable anyway.  A guess.  I have removed all gh-actions actions for the 6.0 branch that mention MacOS, just to be sure.  Don't know if that helps for this one.
But at least some changes are needed.

**Comment by mauritsvanrees** [comment]
There were also problems installing `charset-normalizer` on all Python versions, for example [this run](https://github.com/plone/buildout.coredev/actions/runs/8822928314/job/24222308271):

```
Getting distribution for 'charset-normalizer==3.3.2'.
root: Downloading https://files.pythonhosted.org/packages/d1/b2/fcedc8255ec42afee97f9e6f0145c734bbe104aac28300214593eb326f1d/charset_normalizer-3.3.2-cp312-cp312-macosx_10_9_universal2.whl#sha256=0b2b64d2bb6d3fb9112bafa732def486049e63de9618b5843bcdd081d8144cd8
While:
  Installing.
  Loading extensions.
  Getting distribution for 'charset-normalizer==3.3.2'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/zc/buildout/buildout.py", line 2252, in main
    getattr(buildout, command)(args)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/zc/buildout/buildout.py", line 697, in install
    self._load_extensions()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/zc/buildout/buildout.py", line 1231, in _load_extensions
    zc.buildout.easy_install.install(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/zc/buildout/easy_install.py", line 971, in install
    return installer.install(specs, working_set)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/zc/buildout/easy_install.py", line 744, in install
    for dist in self._get_dist(req, ws):
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/zc/buildout/easy_install.py", line 581, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/zc/buildout/easy_install.py", line 1948, in _move_to_eggs_dir_and_compile
    assert newdist is not None  # newloc above is missing our dist?!
           ^^^^^^^^^^^^^^^^^^^
AssertionError
```

The root problem is likely described here in buildout, two years ago:
https://github.com/buildout/buildout/issues/609#issuecomment-1317190892
Something with `universal2` wheels, and Buildout not converting this correctly to an egg.

I "fix" this with a [workaround](https://github.com/plone/buildout.coredev/pull/924/files#diff-788bc5385df90eafe44d7e6f8c5274b58abb5c25165d16694b5bfa8500035f53L39-R45) that helped before:

        export _PYTHON_HOST_PLATFORM="macosx-11-x86_64"
